### ISSUE TITLE
improve results

### ISSUE THREAD

**Issue by marvis** [eric-yyjau/pytorch-superpoint#12]
Hi @eric-yyjau,

Thanks for your great work to reproduce SuperPoint in pytorch.  

I fellow your training scripts many times, but always get bad result.  The first gif image is the  result of my model. The second gif image is the result of your released model.
![out](https://user-images.githubusercontent.com/679954/81135980-bf8b6b00-8f8c-11ea-8d85-00152a653606.gif)
![out2](https://user-images.githubusercontent.com/679954/81135983-c1edc500-8f8c-11ea-8877-524ec1386aa8.gif)

I exactly fellow the three training steps of this repository. My superpoint model is trained on coco data. Your model is from logs/superpoint_coco_heat2_0/checkpoints/superPointNet_170000_checkpoint.pth.tar. 

I am confused about why my detected key points is far less than yours. 

Do you have any suggestions for me?  Thanks!

**Comment by FurKan7** [comment]
Hey, @marvis how did you test it like you've showed?
