### ISSUE TITLE
About  load the Coco dataset when export（export.py）

### ISSUE THREAD

**Issue by zhanggaojian** [eric-yyjau/pytorch-superpoint#13]
Hello ，I am  sorry to bother you again. I have met new problems. When export the Coco dataset, the dataset is 'Coco' in config file. While dataset is 'coco' in dataset loader. The file in ./datasets is also 'Coco.py' . Looking forward to your reply! Thanks!

https://github.com/eric-yyjau/pytorch-superpoint/blob/86b9621888e7c91801a5e9de889009573f407e45/configs/magicpoint_coco_export.yaml#L1-L2

https://github.com/eric-yyjau/pytorch-superpoint/blob/86b9621888e7c91801a5e9de889009573f407e45/export.py#L302

https://github.com/eric-yyjau/pytorch-superpoint/blob/86b9621888e7c91801a5e9de889009573f407e45/export.py#L349

https://github.com/eric-yyjau/pytorch-superpoint/blob/86b9621888e7c91801a5e9de889009573f407e45/utils/loader.py#L128-L130

**Comment by eric-yyjau** [comment]
Hi @zhanggaojian ,

Thank you for your feedback. Actually 'coco' is replaced by 'Coco'.
The file name matches the class name to import as a module (define the name in config file).
I updated the code and merged to master.

**Comment by zhanggaojian** [comment]
@eric-yyjau ，Thanks for your reply. I am sorry to bother you again. I have some question about pretrained model.Which  pretrained model need to be loading when running the step 3 in config files?
