### ISSUE TITLE
Loading pretrained weight

### ISSUE THREAD

**Issue by ins7itia** [eric-yyjau/pytorch-superpoint#14]
Hello,
Thank you for your effort to make it!

I found something strange in Train_model_frontend.py:
https://github.com/eric-yyjau/pytorch-superpoint/blob/86b9621888e7c91801a5e9de889009573f407e45/Train_model_frontend.py#L201

I guess it checks whether the suffix is '.pth' or 'tar.gz'. If that's correct, above code should be changed like:
```python
mode = "" if path[-4:] == ".pth" else "full"
```

Thanks again, please let me know if I miss something!

**Comment by eric-yyjau** [comment]
Hi @ins7itia,

Yeah you're right. Thanks for pointing out.
Sorry for the mistake. I've updated and merged to master. Please let me know how it works.

**Comment by ins7itia** [comment]
No problem at all, @eric-yyjau . Thank you for the fast feedback.

I have tested with changed code and it passed fine. I didn't test with .pth file through training since I don't have the weight, but I'm pretty sure the updated is fine! I'll close the issue:)
