### ISSUE TITLE
about kitti dataset train

### ISSUE THREAD

**Issue by wrking** [eric-yyjau/pytorch-superpoint#15]
@eric-yyjau 
Thank you for your great work!
I notice that in Kitti_inh.py,there are two files called "cam.txt" and "imu_pose_matrixs.txt" which are not in Kitti dataset,could you offer me these?
Looking forward to your reply.Thanks!

**Comment by eric-yyjau** [comment]
Hi @wrking,

Thank you for your reply.
Sorry I think the two files, "cam.txt" and "imu_pose_matrixs.txt",  are redundant.
I fixed it by putting dummy value to the two entries.
Please let me know if it works.

**Comment by wrking** [comment]
I test it and it works! Thank you! @eric-yyjau

**Comment by eric-yyjau** [comment]
Awesome. Thank you!
