### ISSUE TITLE
Have you reproduced the results showed by rpautrat

### ISSUE THREAD

**Issue by shaofengzeng** [eric-yyjau/pytorch-superpoint#2]
Great work! 
Thanks for sharing. Can i use your code to reproduce the results showed in https://github.com/rpautrat/SuperPoint
 Looking forward to your reply

**Comment by eric-yyjau** [comment]
Hi, which part of results are you focusing on?
We have reproduced the table as the paper.
![image](https://user-images.githubusercontent.com/17765629/72033459-55f49c00-32cd-11ea-9f5d-49d458e2a79a.png)

If you'd like to evaluate on HPatches for illumination changes or viewpoint changes, you can change the config file to do so.
Thanks.
