### ISSUE TITLE
evaluation score

### ISSUE THREAD

**Issue by coper16** [eric-yyjau/pytorch-superpoint#24]
Hi, thank you for your great work!
I finished SuperPoint training by your code.
Thank you very much.

I understand that your code is based on "https://github.com/rpautrat/SuperPoint".
And so I would like to ask 3 question.

1)
I tried to use your evaluation code and pretrain model(by MagicLeap).
I use H-Patches-v(only view point change) evaluation dataset.
![スクリーンショット 2020-08-30 21 50 12](https://user-images.githubusercontent.com/54351314/92194507-d217a180-eea5-11ea-8b49-fb297543268f.png)
and so, why is this homography estimation score(threshold 3 pix)  lower than  the score of  pretrain model by evaluation code of https://github.com/rpautrat/SuperPoint?
![スクリーンショット 2020-09-04 10 09 56](https://user-images.githubusercontent.com/54351314/92194832-8ca7a400-eea6-11ea-978e-6d8495262359.png)
I think H-Patches-all(view point change and illumination change) score may have same trend.

2)
Is there difference between your training procedure and https://github.com/rpautrat/SuperPoint?
for example, the number of steps of Homographic Adaption procedure, MS-COCO data augmentation…
I would like to know the precautions when changing from using code of https://github.com/rpautrat/SuperPoint to using your code.

3)
What is difference between SuperPointNet_gauss2 model and SuperPointNet model?

Best,

**Comment by eric-yyjau** [comment]
Hi @coper16 ,

Thank you for your questions.
1. I think the superpoint repo updates their algorithms and results in 2020.
When I'm working on the project in 2019, the results are similar.
https://github.com/rpautrat/SuperPoint/tree/13c678d08dbd5b1ebec50fae2dc706262baf47f3

2. 
The threshold of NN matching, NMS radius, and number of keypoints may affect the results.
Besides, I think they have changed some training details.
Please let me know if you see the differences.

3. 
`SuperPointNet` is an experiment using `groupNorm`.
`SuperPointNet_gauss2` is the latest model with some additional functions for keypoint extraction and matching. These are useful in my [deepFEPE](https://github.com/eric-yyjau/pytorch-deepFEPE/) paper.

Thanks.

**Comment by coper16** [comment]
Thank you for your reply.

I see.
There is one point that I want to know about question(1).

In 2019, could you get same result by pretrain model(by magicleap) score(H-Patches viewpoint change score) of https://github.com/rpautrat/SuperPoint/tree/13c678d08dbd5b1ebec50fae2dc706262baf47f3 ?
My score is 0.60.

<img width="718" alt="スクリーンショット 2020-09-09 9 07 37" src="https://user-images.githubusercontent.com/54351314/92539486-8cc7eb00-f27c-11ea-9e7e-4c9c11be7ab0.png">

**Comment by eric-yyjau** [comment]
Hi @coper16 ,

I didn't have the evaluation for viewpoint and illumination separately.
The results I had is 0.77 under threshold 3 for the whole H-Patches dataset.
![image](https://user-images.githubusercontent.com/17765629/92620998-28a32800-f278-11ea-8e2d-93f1807f0be6.png)

Thanks.

**Comment by coper16** [comment]
Sorry for the late reply…
I found the difference point between 2019 and 2020 of https://github.com/rpautrat/SuperPoint.
The details of the bug were written in https://github.com/rpautrat/SuperPoint/issues/117.
There may be this bug in your code.
This is just a report.
Thanks.
