### ISSUE TITLE
why the size of the descriptor is 256 float?

### ISSUE THREAD

**Issue by lijianglong2018** [eric-yyjau/pytorch-superpoint#25]
Thank you for your great work!
I wonder why the size of the descriptor is 256 float? Have you tested the other size ?

Thanks in advance! Really hope to get your reply!

**Comment by eric-yyjau** [comment]
Hi @lijianglong2018,

Actually the descriptor size is designed by the original superPoint paper.
Please check it out here: https://arxiv.org/abs/1712.07629
Sorry I don't have more insight about the dimension of the descriptors.
