### ISSUE TITLE
Pretraining the MagicPoint with GPU

### ISSUE THREAD

**Issue by whoamibro** [eric-yyjau/pytorch-superpoint#28]
First of all, Thank you for the amazing work for translating tensorflow to pytorch.

I'm currently training the MagicPoint Network with Synthetic Shapes dataset. 
When MagicPoint starts training based on your code, I found out that it doesn't use any GPU power. 

Is this code, supports GPU training?

**Comment by Y-pandaman** [comment]
hello，I met the same problem as you. Have you solved it? I checked the GPU status with the command  `nvidia-smi `, I found out that it doesn't use any GPU power. my pytorch version is 1.5.0+cu101, torchvision version is 0.6.0+cu101，looking forward to your reply.
