### ISSUE TITLE
Diff between SuperPointNet and SuperPointNet_gauss2

### ISSUE THREAD

**Issue by heiko134470** [eric-yyjau/pytorch-superpoint#31]
Hi, firstly I would like to thank you for your work on this repository.

SuperPointNet
![image](https://user-images.githubusercontent.com/58684478/99211527-6fc31180-2803-11eb-9914-ac85bfd8d44a.png)

SuperPointNet_gauss2
![image](https://user-images.githubusercontent.com/58684478/99211532-72be0200-2803-11eb-8428-2d26cb270512.png)

Could you explain:
why do you use SuperPointNet, rather than SuperPointNet_gauss2?
What is difference between SuperPointNet and SuperPointNet_gauss2. The above pictures show that there is no difference in terms of network structure.

**Comment by eric-yyjau** [comment]
Hi @heiko134470 

Sorry for my late reply.
Yeah. The network structure is mostly the same.
`SuperPointNet` is for the experimental purpose. I did some experiments using group norm.
Is it not used our training pipeline.

We use `SuperPointNet_gauss2 ` (https://github.com/eric-yyjau/pytorch-superpoint/blob/d0a9b3c553be4837e9f6651d67c3ead1e39bbcc4/configs/superpoint_coco_train_heatmap.yaml#L60)

`gauss` here means using gaussian kernel on the labels. The final prediction would go through the sof argmax function to have subpixel accuracy.
