### ISSUE TITLE
about output HPatches image

### ISSUE THREAD

**Issue by coper16** [eric-yyjau/pytorch-superpoint#35]
Hello.
Thank you for your great works.

I tried to train SuperPoint & HPatches evaluation by your code.
and, I checked output matching image.

I find key point detected at the place that is clearly not key point(figure 1&2).
![5cv_b](https://user-images.githubusercontent.com/54351314/103957984-4da89880-518f-11eb-9d63-75c692d951c7.png)
![15cv_b](https://user-images.githubusercontent.com/54351314/103957988-4f725c00-518f-11eb-8120-9833ab6fe0ad.png)

Did you output similar images?
And, Do you have any idea how to improve it?

**Comment by eric-yyjau** [comment]
Hi @coper16,

Did you use my model or the model trained by yourself?
I didn't remember this exact example, but my testing on HPatches should give better results.

From my scripts, I have visualization during training. It may help to open up tensorboard and check if the training works fine.

**Comment by coper16** [comment]
I trained by myself.
Ok.I will check tensorboard.
thanks:)
