### ISSUE TITLE
Bugs in Hpatches evaluation framework

### ISSUE THREAD

**Issue by LiZhiqiang0** [eric-yyjau/pytorch-superpoint#36]
Hello, I'm sorry to disturb you. 
Your project is rebuilt based on [rpautrat/SuperPoint,](https://github.com/rpautrat/SuperPoint/) but rpautrat/SuperPoint has some bugs in hpatches evaluation [Bugs in Hpatches evaluation framework.](https://github.com/rpautrat/SuperPoint/issues/117)
I wonder whether you will fix these bugs

**Comment by eric-yyjau** [comment]
Hi @LiZhiqiang0,

Thank you for your question.
I did notice the cropping issue while I was implementing this.
I use the whole image instead for simplicity. I handled the scaling of homography:
https://github.com/eric-yyjau/pytorch-superpoint/blob/4ff74df8fa3c10ce9eb9fdc561f787d9e8bc9691/datasets/patches_dataset.py#L100

So I think there should be no bugs in my evalution.
Let me know if you see something wrong.
Thanks.
