### ISSUE TITLE
PR to kornia?

### ISSUE THREAD

**Issue by ducha-aiki** [eric-yyjau/pytorch-superpoint#39]
Hi,

Thank you for the great repo! Would you be interested in making your SuperPoint pretrained model available via kornia?  https://github.com/kornia/kornia

Kornia is "OpenCV in PyTorch"  and we already have classical descriptors like SIFT, pretrained [HardNet](https://kornia.readthedocs.io/en/latest/feature.html#kornia.feature.HardNet) and SOSNet from the authors. I believe that could make more people use your model and cite your work.

Best, Dmytro.

**Comment by eric-yyjau** [comment]
Hi @ducha-aiki,

Thank you for your suggestion. I'll take a look.
I'm not sure if I have the availability to work on it for now, but I'll keep that in mind.

Best,
You-Yi
