### ISSUE TITLE
Something wrong with file "evaluate_frontend.py"

### ISSUE THREAD

**Issue by shaofengzeng** [eric-yyjau/pytorch-superpoint#4]
Help. please check file "evaluate_frontend.py". I load your code in pycharm, there are many unsolved references...

**Comment by eric-yyjau** [comment]
Sorry for the delay. I’ll check ASAP.

**Comment by eric-yyjau** [comment]
Hi, thank you.
Sorry I forgot to delete the unfinished file. Please refer to `evaluation.py` for evaluation.
https://github.com/eric-yyjau/pytorch-superpoint/tree/sp_release1211_clean#4-export-evaluate-the-metrics-on-hpatches
