### ISSUE TITLE
Which mask_3d_flattened is used?

### ISSUE THREAD

**Issue by DaddyWesker** [eric-yyjau/pytorch-superpoint#41]
Hello, i can't think of better name for this, but oh well. Here is the case:

File Train_model_heatmap.py. Line 301. Here you're using mask_3d_flattened as mask_desc. THough, if bool value if_warp == True, then you're replacing value of this mask_3d_flattened (which was defined previously as mask_3D_flattened = self.getMasks(mask_2D, self.cell_size, device=self.device) ) with new value, line 278, mask_3D_flattened = self.getMasks(mask_warp_2D, self.cell_size, device=self.device). So, in the further calculations, you're using warped mask instead of normal one. Is that algorithmically right? 

Thanks in advance fr explanations.

**Comment by eric-yyjau** [comment]
Hi @DaddyWesker ,

I'm not sure if I understand your question correctly.

Are you asking why I'm overwriting the value of `mask_3D_flattened` when `if_warp == True`?

When `if_warp == True`, `mask_3D_flattened` is overwriiten when calculating the warped descriptor loss.
`mask_desc` is only used to calculate that loss.
https://github.com/eric-yyjau/pytorch-superpoint/blob/4ff74df8fa3c10ce9eb9fdc561f787d9e8bc9691/Train_model_heatmap.py#L301

If `if_warp == False` or `lambda_loss <= 0`, we won't calculate descriptor loss.
https://github.com/eric-yyjau/pytorch-superpoint/blob/4ff74df8fa3c10ce9eb9fdc561f787d9e8bc9691/Train_model_heatmap.py#L319

Hope this helps.
Best,

**Comment by DaddyWesker** [comment]
Alright. Thanks for the explanation.
