### ISSUE TITLE
Superpoint model on mobile devices

### ISSUE THREAD

**Issue by cumtchenchang** [eric-yyjau/pytorch-superpoint#5]
Hi, thank you for your good work. Have you considered how to improve the speed and apply it to mobile devices? such as replace VGG with MobileNet. If you have tried or have ideas about it, please tell me. Thank you, sincerely.

**Comment by eric-yyjau** [comment]
Hi, thank you for your message.
I didn't try to improve the speed. If you'd like to do so, you can put a network under `models/` and edit the config file to train using the new network.
