### ISSUE TITLE
code can not support torch 1.1

### ISSUE THREAD

**Issue by cumtchenchang** [eric-yyjau/pytorch-superpoint#6]
Hi, thank you for your good work. I test your code and encounter an error:
pytorch-superpoint/utils/utils.py", line 351, in inv_warp_image_batch
    warped_img = F.grid_sample(img, src_pixel_coords, mode=mode, align_corners=True)
TypeError: grid_sample() got an unexpected keyword argument 'align_corners

I find align_corners is used in pytorch after 1.3:
torch.nn.functional.grid_sample(input, grid, mode='bilinear', padding_mode='zeros', align_corners=None)
But my cluster only support cuda9.0, which does not support pytorch 1.3.

I tried to change your code, remove align_corners of grid_sample function under Pytorch 1.1, but there is another error:
 args.func(config, output_dir, args)
  File "train4.py", line 42, in train_base
    return train_joint(config, output_dir, args)
  File "train4.py", line 95, in train_joint
    train_agent.train()
  File "/home/test/pytorch-superpoint/Train_model_frontend.py", line 277, in train
    loss_out = self.train_val_sample(sample_train, self.n_iter, True)
  File "/home/test/pytorch-superpoint/Train_model_heatmap.py", line 385, in train_val_sample
    loss.backward()
  File "/home/anaconda3/envs/py36-sp/lib/python3.6/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/anaconda3/envs/py36-sp/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Function AddBackward0 returned an invalid gradient at index 0 - expected type torch.cuda.FloatTensor but got torch.cuda.LongTensor

Do you have code support lower versions or how to solve the above problems? Thank you.

**Comment by eric-yyjau** [comment]
I used to develop under torch1.1. Let me test and get back to you. Thank you.

**Comment by eric-yyjau** [comment]
Hi, 
Thank you for your patience.
I found the bug of loss type and corrected it in master's branch.
https://github.com/eric-yyjau/pytorch-superpoint/blob/86b9621888e7c91801a5e9de889009573f407e45/Train_model_heatmap.py#L288

Also, I created a branch for torch1.1 (just remove all 'align_corners').

https://github.com/eric-yyjau/pytorch-superpoint/tree/sp_release1211_clean_torch1.1
Please let me know if there's any question.

**Comment by cumtchenchang** [comment]
@eric-yyjau  Hi, thank you for your response. I will test it as soon as possible after the Chinese New Year. After test, I will add new response. Thank you.
