### ISSUE TITLE
train coco  no iteration

### ISSUE THREAD

**Issue by dachengai** [eric-yyjau/pytorch-superpoint#66]
train coco  no  error  ,but  no iteration

![image](https://user-images.githubusercontent.com/8870735/141283062-cd2b46d3-9591-4cdc-859c-044f7f54318d.png)

**Comment by doriz3** [comment]
hello,  @dachengai I also encountered this problem now,  how did you solved it later? thank you very much!
![1](https://github.com/eric-yyjau/pytorch-superpoint/assets/114843645/9797ef5f-2e35-4a65-8f48-cda3569c936c)

**Comment by doriz3** [comment]
Look forward to your feedback. Thanks!
