### ISSUE TITLE
Magic point training is sluggish. 

### ISSUE THREAD

**Issue by saunair** [eric-yyjau/pytorch-superpoint#74]
Hey authors, great repo and thanks for making this public!
I was training magic points over the synthetic shapes, but the training is taking too long. It's been running for more than 24 hrs. 

It seems there is multi-GPU support, but the GPU usage is like 4% on 3 2080s. What am I missing here?

**Comment by saunair** [comment]
Increasing the number of workers in the config helped!

**Comment by cxmscb** [comment]
> Increasing the number of workers in the config helped!

I meet the same problem. Could you tell me the number of workers you set?

**Comment by EndlessPeak** [comment]
It should depend on how many cores (threads,actually) your cpu have.
