### ISSUE TITLE
server shut down when runing export.py

### ISSUE THREAD

**Issue by Yf-Xue** [eric-yyjau/pytorch-superpoint#8]
Hi. Really great work. I just finished the pretrain part and begin to do export on COCO. Everything goes on well until it load several pictures and the server suddenly shut down. I tried several times. It cannot be GPU overheat cause it shut down at the very beginning. Do you have any idea why this happens? Maybe it's the CUDA version problem?

**Comment by eric-yyjau** [comment]
Sorry for the late reply. Do you have any error message to share? So that I can try to help.
Thank you.

**Comment by Yf-Xue** [comment]
No. It just suddenly reboost during the middle of training, which also confused me. Maybe I can try using small batch size

**Comment by eric-yyjau** [comment]
I see. Let me know if you see anything I could help.
